# Generated by Django 4.0.4 on 2022-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
