# Generated by Django 4.0.4 on 2022-07-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billing_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='item',
        ),
    ]
