# Generated by Django 4.0.4 on 2022-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_billing_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
