# Generated by Django 4.0.4 on 2022-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billing_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='shipping_type',
            field=models.CharField(default='Standard Shipping 5-10 days', max_length=200),
        ),
    ]
