# Generated by Django 4.0.4 on 2022-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
