# Generated by Django 4.0.4 on 2022-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
