# Generated by Django 4.0.4 on 2022-07-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
